server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/point?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: yj_mysql

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

#  thymeleaf:
    prefix: classpath:/templates/A
    suffix: .html
    cache: false


mybatis:
  type-aliases-package: com.point.www√Ö
  mapper-locations: mybatis/mapper/**/*.xml

devtools:
  # Auto Restart
  restart:
    enabled: true
    additional-exclude: static/**,public/**






